language: java

dist: jammy

jdk:
  - openjdk17

cache:
  directories:
    - $HOME/.m2

env:
  global:
    - SPRING_PROFILES_ACTIVE=test
    - TRAVIS_DEMO_FORCE_FAIL=true
before_install:
  - chmod +x mvnw
script:
  - ./mvnw -B test

